### ISSUE TITLE
SQL issues utf8mb4

### ISSUE THREAD

**Issue by petrk94** [Edraens/EdPaper#3]
Hello,

I have tried to install it, but I get this, is 

$ php artisan migrate

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1115 Unknown character s
  et: 'utf8mb4' (SQL: select * from information_schema.tables where table_sch
  ema = petrk_edpaper and table_name = migrations)

In MySqlConnector.php line 56:

  SQLSTATE[42000]: Syntax error or access violation: 1115 Unknown character s
  et: 'utf8mb4'

Can you help?

**Comment by eahlys** [comment]
It seems that your database doesn't allow the utf8mb4 charset, which is needed for some special characters in pastes.
Can you give me more infos on your OS ? Are you using MySQL ?

**Comment by petrk94** [comment]
I could identify the problem through a blogpost by someone who had the same problem.
My hoster is Uberspace and Im on a CentOS 6 Shared Host where MySQL 5.1.73 is in use.
As alternative I can use MariaDB, but is your EdPaper working with MariaDB or not?

**Comment by eahlys** [comment]
Yes, the demo on paper.edra.ovh is running on MariaDB

**Comment by petrk94** [comment]
Alright, I have set it up, the php artisan migration worked successfully, but Im facing the issue with the public folder.
I have running it on a subdomain edpaper.xxx.de but even by setting in the public folder RewriteBase / to the .htaccess, it doesnt work.
Do you have any idea what the reason is?
Thanks

**Comment by eahlys** [comment]
Glad to know that MariaDB worked with you too :)

What do you mean by "it doesn't work" ? Can you give me the error in apache's log ?

**Comment by petrk94** [comment]
I dont get more information from the error log

[Sun Mar 18 23:30:29 2018] [error] [client xx.xx.xx.xx] Directory index forbidden by Options directive: edpaper.xxx.de
[Sun Mar 18 23:30:29 2018] [error] [client xx.xx.xx.xx] Directory index forbidden by Options directive: edpaper.xxx.de

By opening the subdomain edpaper.xxx.de I get a forbidden.
It work when I got on edpaper.xxx.de/public/ but login function doesnt work, due it want to open edpaper.xxx.de/login but this doesnt work due Im in edpaper.xxx.de/public/
So I dont know what the problem cause.

**Comment by eahlys** [comment]
Is your DocumentRoot pointing on the public directory ?

**Comment by petrk94** [comment]
Im not sure what you mean exactly.
On the server I have the subdomain on /var/www/virtual/petrk/edpaper.xxx.de
the DocumentRoot is in the /var/www/virtual/petrk/html/ folder, I think

**Comment by eahlys** [comment]
Your subdomain needs to be on /var/www/virtual/petrk/edpaper.xxx.de/public/

**Comment by petrk94** [comment]
Hmm, I dont understand this.
I have edpaper.xxx.de as subdomain folder, but I can only get a page when I open edpaper.xxx.de/public/ but there I can not login, because the login tries to open edpaper.xxx.de/login
So it doesnt work.

**Comment by nucreativa** [comment]
Go to config/database.php and replace these two lines with these
```
'charset' => 'utf8',  
'collation' => 'utf8_unicode_ci',`
```

source : https://stackoverflow.com/questions/41835923/syntax-error-or-access-violation-1115-unknown-character-set-utf8mb4

**Comment by petrk94** [comment]
Thanks for adding this solution, but I dropped the interest in it and chose another solution. Thanks anyway
